/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRepomedicHealthRouteImport } from './routes/api/repomedic/health'
import { Route as ApiRepomedicRunRouteImport } from './routes/api/repomedic/run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepomedicHealthRoute = ApiRepomedicHealthRouteImport.update({
  id: '/api/repomedic/health',
  path: '/api/repomedic/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepomedicRunRoute = ApiRepomedicRunRouteImport.update({
  id: '/api/repomedic/run',
  path: '/api/repomedic/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/repomedic/health': typeof ApiRepomedicHealthRoute
  '/api/repomedic/run': typeof ApiRepomedicRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/repomedic/health': typeof ApiRepomedicHealthRoute
  '/api/repomedic/run': typeof ApiRepomedicRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/repomedic/health': typeof ApiRepomedicHealthRoute
  '/api/repomedic/run': typeof ApiRepomedicRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/repomedic/health' | '/api/repomedic/run'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/repomedic/health' | '/api/repomedic/run'
  id: '__root__' | '/' | '/api/repomedic/health' | '/api/repomedic/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRepomedicHealthRoute: typeof ApiRepomedicHealthRoute
  ApiRepomedicRunRoute: typeof ApiRepomedicRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repomedic/health': {
      id: '/api/repomedic/health'
      path: '/api/repomedic/health'
      fullPath: '/api/repomedic/health'
      preLoaderRoute: typeof ApiRepomedicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repomedic/run': {
      id: '/api/repomedic/run'
      path: '/api/repomedic/run'
      fullPath: '/api/repomedic/run'
      preLoaderRoute: typeof ApiRepomedicRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRepomedicHealthRoute: ApiRepomedicHealthRoute,
  ApiRepomedicRunRoute: ApiRepomedicRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
